[package]
name = "temp"
version = "0.1.0"
edition = "2021"
autobins = true
[[bin]]
name = "example_estruc"
path = "src/EstructureChapter/example_estruct.rs"
[[bin]]
name = "ownership_struct"
path = "src/EstructureChapter/ownership_struct.rs"
[dependencies]
